version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo-python
    ports:
      - "27018:27017"  # Cambia el puerto 27017 a 27018
    volumes:
      - mongo-data:/data/db

  fastapi:
    build:
      context: .
    container_name: fastapi
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://mongo:27017/clientPortfolioDB

volumes:
  mongo-data:
