version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo-python
    ports:
      - "27018:27017"  # Cambia el puerto 27017 a 27018
    volumes:
      - mongo-data:/data/db
    command: mongod
    healthcheck:
      test: ["CMD", "mongo", "--port", "27017", "--eval", "db.adminCommand('ping')"]
      timeout: 5s
      retries: 5

  fastapi:
    build:
      context: .
    container_name: fastapi
    command: ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      MONGO_URI: mongodb://mongo:27017/clientPortfolioDB

volumes:
  mongo-data:
